networks:
  dev:
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - frontend
    networks:
      - dev
    environment:
      - HOST=${SERVER_HOST}
      - PR=${PARAM}

  frontend:
    build:
      context: ./frontend
    networks:
      - dev
    environment:
      - HOST={$SERVER_HOST}
      - PR=${PARAM}
  
    